# Generated by Django 5.1.3 on 2024-11-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0006_venta_direccion_venta_instalacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='cantidadporproducto',
            field=models.IntegerField(default=1),
        ),
    ]
