# Generated by Django 5.1.3 on 2024-11-23 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0009_alter_venta_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='idempleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fs.empleado'),
        ),
    ]
