# Generated by Django 5.1.3 on 2024-11-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0010_alter_bodega_idempleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='precioinstalacion',
            field=models.FloatField(default=0),
        ),
    ]
