# Generated by Django 5.1.3 on 2024-11-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0002_cliente_empleado_marca_proveedor_bodega_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='estado',
            field=models.BooleanField(),
        ),
    ]
