# Generated by Django 5.1.3 on 2024-11-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0003_alter_bodega_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodega',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='bodega',
            name='capacidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
