# Generated by Django 5.1.3 on 2024-11-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0004_remove_bodega_cantidad_bodega_capacidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fechadeactualizacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
