# Generated by Django 5.1.3 on 2024-11-22 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fs', '0007_detalleventa_cantidadporproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
    ]
